import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import type { VetReport as VetReportData, VetShare, VetShareStage, VetShareWithStatus } from '@connected-care/shared';
import { api } from '../api/client';
import { PetAvatar } from '../components/PetAvatar';
import { ShareDialog } from '../components/ShareDialog';
import { TrendCard } from '../components/TrendCard';
import { UrgencyBadge } from '../components/UrgencyBadge';
import { TREND_METRICS } from '../metrics';

const STAGE_CHIP: Record<VetShareStage, { label: string; cls: string }> = {
  sent: { label: '📤 Sent', cls: 'bg-cream text-gray-500' },
  delivered: { label: '📬 Delivered', cls: 'bg-tier-monitor-soft text-tier-monitor' },
  viewed: { label: '👀 Viewed by clinic', cls: 'bg-tier-attention-soft text-tier-attention' },
  reviewed: { label: '✅ Reviewed', cls: 'bg-safe-soft text-safe' },
};

function compactSummary(report: VetReportData): string {
  const lines = [
    `Vet report for ${report.pet.name} — generated ${new Date(report.generated_at).toLocaleString()}`,
    '',
    report.summary.text,
    '',
    'Active insights:',
    ...(report.active_insights.length > 0
      ? report.active_insights.map((i) => `- [${i.urgency}] ${i.summary}`)
      : ['- none']),
    '',
    'Generated by Connected Care (demo). Device-data pattern summary — not a diagnosis.',
  ];
  return lines.join('\n');
}

async function copyText(text: string): Promise<boolean> {
  try {
    // navigator.clipboard needs a secure context; localhost qualifies, but a
    // LAN-IP http demo doesn't — fall back to the hidden-textarea trick.
    if (navigator.clipboard) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through */
  }
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  const ok = document.execCommand('copy');
  document.body.removeChild(ta);
  return ok;
}

export function VetReport() {
  const { petId } = useParams<{ petId: string }>();
  const [report, setReport] = useState<VetReportData | null>(null);
  const [shares, setShares] = useState<VetShareWithStatus[]>([]);
  const [shareOpen, setShareOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (petId) void api.getVetReport(petId).then(setReport);
  }, [petId]);

  // The share stages advance server-side with time (sent → delivered → viewed
  // → reviewed), so poll while the page is open to close the loop live.
  useEffect(() => {
    if (!petId) return;
    const load = () => void api.getVetShares(petId).then(setShares).catch(() => undefined);
    load();
    const t = setInterval(load, 30_000);
    return () => clearInterval(t);
  }, [petId]);

  if (!report) return <p className="p-8 text-gray-400">Assembling report…</p>;

  const onShared = (share: VetShare) => {
    setReport({ ...report, shares: [share, ...report.shares] });
    void api.getVetShares(share.pet_id).then(setShares).catch(() => undefined);
  };

  const copySummary = async () => {
    if (await copyText(compactSummary(report))) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const emailToVet = () => {
    // mailto bodies truncate around ~2000 chars in some clients — stay under.
    const body = encodeURIComponent(compactSummary(report)).slice(0, 1800);
    // Recorded as a digital share too, fire-and-forget.
    void api.shareVetReport(report.pet.id, { recipient: 'Email to my vet', method: 'email' }).then(onShared);
    window.location.href = `mailto:?subject=${encodeURIComponent(`${report.pet.name} — Connected Care report`)}&body=${body}`;
  };

  const seriesFor = (metric: string) => report.metrics.find((m) => m.metric === metric) ?? null;

  return (
    <div className="mx-auto max-w-3xl space-y-4">
      <Link to={`/pets/${report.pet.id}`} className="inline-block text-sm font-bold text-gray-400 hover:text-charcoal print:hidden">
        ← Back to {report.pet.name}
      </Link>

      <div className="flex flex-wrap items-center gap-2 print:hidden">
        <button
          onClick={() => setShareOpen(true)}
          className="rounded-full bg-brand px-5 py-2.5 font-extrabold text-brand-ink shadow-sm hover:bg-brand-dark"
        >
          📤 Send to my vet
        </button>
        <button
          onClick={() => void copySummary()}
          className="rounded-full border border-black/10 bg-card px-4 py-2.5 text-sm font-bold hover:bg-cream"
        >
          {copied ? '✓ Copied' : 'Copy summary'}
        </button>
        <button
          onClick={emailToVet}
          className="rounded-full border border-black/10 bg-card px-4 py-2.5 text-sm font-bold hover:bg-cream"
        >
          Email
        </button>
        <button
          onClick={() => window.print()}
          className="rounded-full border border-black/10 bg-card px-4 py-2.5 text-sm font-bold hover:bg-cream"
        >
          Print
        </button>
      </div>

      <article className="vet-report rounded-2xl bg-card p-6 shadow-sm sm:p-8">
        <header className="flex flex-wrap items-center gap-4 border-b border-black/5 pb-5">
          <PetAvatar petId={report.pet.id} species={report.pet.species} hasPhoto={report.pet.has_photo} size="sm" />
          <div>
            <h1 className="text-2xl font-extrabold">{report.pet.name} — Veterinary Report</h1>
            <p className="text-sm text-gray-500">
              {report.pet.breed_name ?? report.pet.species}
              {report.pet.age_years !== null && ` · ${report.pet.age_years} years`}
              {report.pet.weight_lbs && ` · ${report.pet.weight_lbs} lbs`}
              {report.pet.sex && ` · ${report.pet.sex}`}
            </p>
            <p className="text-xs text-gray-400">
              Generated {new Date(report.generated_at).toLocaleString()} · last {report.window_days} days of device
              data
            </p>
          </div>
          <span className="ml-auto rounded-full bg-navy px-2.5 py-1 text-[10px] font-bold tracking-widest text-brand">
            DEMO
          </span>
        </header>

        <section className="mt-5">
          <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">
            Summary for your veterinarian
          </h2>
          <p className="mt-2 text-sm leading-relaxed">{report.summary.text}</p>
          <p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-gray-300">
            {report.summary.mode === 'claude' ? 'Generated by Claude' : 'Generated offline from device data'} · not a
            diagnosis
          </p>
        </section>

        <section className="mt-6">
          <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">Active insights</h2>
          {report.active_insights.length === 0 ? (
            <p className="mt-2 text-sm text-gray-400">No active insights.</p>
          ) : (
            <ul className="mt-2 space-y-3">
              {report.active_insights.map((i) => (
                <li key={i.id} className="rounded-xl bg-cream p-3 text-sm">
                  <UrgencyBadge urgency={i.urgency} />
                  <p className="mt-1.5">{i.summary}</p>
                  <p className="mt-1 text-xs text-gray-500">Recommended: {i.recommended_action}</p>
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="mt-6">
          <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">
            14-day trends <span className="font-semibold normal-case">(yellow band = personal baseline range)</span>
          </h2>
          <div className="mt-2 grid gap-3 sm:grid-cols-2">
            {TREND_METRICS.map((t) => (
              <TrendCard key={t.metric} label={t.label} unit={t.unit} series={seriesFor(t.metric)} />
            ))}
          </div>
        </section>

        <section className="mt-6">
          <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">Personal baselines</h2>
          <div className="mt-2 overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="text-xs uppercase tracking-wide text-gray-400">
                  <th className="py-1.5 pr-3">Metric</th>
                  <th className="py-1.5 pr-3">Mean</th>
                  <th className="py-1.5 pr-3">± Stdev</th>
                  <th className="py-1.5 pr-3">Samples</th>
                  <th className="py-1.5">Status</th>
                </tr>
              </thead>
              <tbody>
                {report.baselines.map((b) => (
                  <tr key={b.metric} className="border-t border-black/5">
                    <td className="py-1.5 pr-3 font-semibold capitalize">{b.metric.replace(/_/g, ' ')}</td>
                    <td className="py-1.5 pr-3">{Math.round(b.mean * 10) / 10}</td>
                    <td className="py-1.5 pr-3">{Math.round(b.stdev * 10) / 10}</td>
                    <td className="py-1.5 pr-3">{b.sample_count}</td>
                    <td className="py-1.5">{b.status === 'established' ? 'established' : 'insufficient data'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {report.breed && (
          <section className="mt-6">
            <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">Breed reference context</h2>
            <p className="mt-2 text-sm">
              Resting heart rate reference for {report.breed.breed_name ?? `${report.pet.species} (generic)`}:{' '}
              <span className="font-bold">
                {report.breed.resting_hr_low}–{report.breed.resting_hr_high} bpm
              </span>
              {report.breed.is_generic_fallback && ' (species-generic profile, reduced confidence)'}
            </p>
            {report.breed.common_conditions.length > 0 && (
              <ul className="mt-1.5 text-sm text-gray-600">
                {report.breed.common_conditions.map((c) => (
                  <li key={c.condition}>
                    <span className="font-semibold capitalize">{c.condition}</span> — {c.typical_onset}
                  </li>
                ))}
              </ul>
            )}
          </section>
        )}

        {report.containment && (
          <section className="mt-6">
            <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">Containment status</h2>
            <p className="mt-2 text-sm">
              {report.containment.state === 'protected'
                ? `Inside the containment boundary; collar checked in ${report.containment.minutes_since_check_in ?? '?'} minutes ago.`
                : report.containment.state === 'breach'
                  ? 'Currently reported OUTSIDE the containment boundary.'
                  : 'Collar signal lost — containment unverified.'}
              {report.containment.battery_pct !== null && ` Collar battery ${report.containment.battery_pct}%.`}
            </p>
          </section>
        )}

        <section className="mt-6 border-t border-black/5 pt-4">
          <h2 className="text-sm font-extrabold uppercase tracking-wider text-gray-400">Share history</h2>
          {shares.length === 0 ? (
            <p className="mt-2 text-sm text-gray-400">Not shared yet.</p>
          ) : (
            <ul className="mt-2 space-y-2 text-sm">
              {shares.map((s) => (
                <li key={s.id}>
                  <span className={`mr-2 rounded-full px-2.5 py-0.5 text-xs font-bold ${STAGE_CHIP[s.stage].cls}`}>
                    {STAGE_CHIP[s.stage].label}
                  </span>
                  <span className="font-bold">{s.recipient}</span> · {new Date(s.shared_at).toLocaleString()} (
                  {s.method})
                  {s.clinic_note && (
                    <p className="mt-1 rounded-xl bg-safe-soft px-3 py-2 text-xs text-safe">💬 {s.clinic_note}</p>
                  )}
                </li>
              ))}
            </ul>
          )}
        </section>
      </article>

      {shareOpen && (
        <ShareDialog
          petId={report.pet.id}
          petName={report.pet.name}
          onShared={onShared}
          onClose={() => setShareOpen(false)}
        />
      )}
    </div>
  );
}
